name: Deploy to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get Build Files
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build
